### ISSUE TITLE
Still redirected to some URLs

### ISSUE THREAD

**Issue by Skane-kun** [igorlogius/stopNaviByRegEx#1]
If try to go to the URL https://www.youtube.com/c/smosh it will still redirect me to https://www.youtube.com/channel/UCY30JRSgfhYXA6i6xX1erWg even when I blacklist the redirect

**Comment by igorlogius** [comment]
## Analysis: 
Looking at the Network traffic and events, no actual webNavigation seems to be involved
Instead the webpage seems to use the History API to "rewrite" the current page url.

## Test
1. install [WebAPI Blocker](https://addons.mozilla.org/en-US/firefox/addon/webapi-blocker) 
2. Disable History API
3. load  https://www.youtube.com/c/smosh  in a newtab

## Result: 
This confirms the assumption
![2021-04-04_15:40:37](https://user-images.githubusercontent.com/67047467/113510663-6a185f00-954b-11eb-8c0e-406d19ea178f.png)

## Verdict
Technically this not a bug with the add-on, but a  website "missusing" a HTML 5 "feature".
By changing the url in such an way while a normal user assumes a webnavigation has happend, since this is the "standard" way most usere know how and why a weburl should and will change. 


## Refs.
- https://developer.mozilla.org/en-US/docs/Web/API/Window/history
- https://developer.mozilla.org/en-US/docs/Web/API/History_API
- https://stackoverflow.com/questions/8560617/how-to-change-url-in-browser-without-navigating-away-from-page

**Comment by igorlogius** [comment]
I might have found a  "terrible" workaround. :smiling_imp:  

@Skane-kun  : 
After i released the next version (0.1.2) , 
be so kind to check if this addresses the issue on youtube as well as on twitter.

Later.

**Comment by igorlogius** [comment]
@Skane-kun 
Did the changes in version 0.1.2 resolve the issue?

**Comment by Skane-kun** [comment]
Oh, yeah. Sorry, I forgot to respond. It works well in most situations except where the HTML 5 feature is misused like you mentioned.
 
If I try to go to youtube.com/c/smosh, it will briefly load the URL, then redirect to the blacklisted URL https://www.youtube.com/channel/UCY30JRSgfhYXA6i6xX1erWg and finish loading that, then it takes you back to your previous URL you were at before you tried to go to youtube.com/c/smosh.

If the tab you are in doesn't have a previous URL to go to, then it will just fully load the blacklisted url page. 

After you described the problem with them misusing the HTML5 feature, it makes me question whether or not the URL https://www.youtube.com/c/smosh even exists. It appears to load that page for a moment before redirecting you to www.youtube.com/channel/UCY30JRSgfhYXA6i6xX1erWg, but if it's just rewriting the page then it isn't a real webpage. 

I have not been able to stay on the page https://www.youtube.com/c/smosh. It either redirects me to the blacklisted url www.youtube.com/channel/UCY30JRSgfhYXA6i6xX1erWg or it keeps me where I was before I tried to go to https://www.youtube.com/c/smosh.

Thanks for your effort.
